### ISSUE TITLE
When dataWynncraftTerritoryList fails to download, fuy.gg logs at insane rate

### ISSUE THREAD

**Issue by MenacingPerson** [Essentuan/fuy.gg#7]
```
[20:31:41] [ForkJoinPool.commonPool-worker-1/WARN]: Failure in net manager [doHandle], processing DL:dataWynncraftTerritoryList, HttpTimeoutException: request timed out
[20:31:41] [ForkJoinPool.commonPool-worker-1/WARN]: Failed to update territory data.
```

When the above error occurs at startup, fuy.gg logs this:

```java
[20:32:04] [ForkJoinPool.commonPool-worker-6/ERROR]: Exception caught during firing event: com/busted_moments/client/models/territory/TerritoryModel
	Index: 1
	Listeners:
		0: LOWEST
		1: ASM: com.busted_moments.client.models.territory.TerritoryModel@1183e952 onMapUpdate(Lcom/busted_moments/client/models/territory/events/MapUpdateEvent;)V
java.lang.NoClassDefFoundError: com/busted_moments/client/models/territory/TerritoryModel
	at com.busted_moments.client.models.territory.__TerritoryModel_onMapUpdate_MapUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at com.wynntils.core.WynntilsMod.postEvent(WynntilsMod.java:68)
	at com.busted_moments.core.events.BaseEvent.post(BaseEvent.java:15)
	at com.busted_moments.client.models.territory.TerritoryModel.lambda$onGameStart$0(TerritoryModel.java:59)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at com.busted_moments.core.Promise.complete(Promise.java:352)
	at com.busted_moments.core.api.internal.Request.fulfill(Request.java:104)
	at com.busted_moments.core.api.HttpScheduler.onRequestSuccess(HttpScheduler.java:72)
	at com.busted_moments.core.api.HttpScheduler.lambda$sendRequest$3(HttpScheduler.java:59)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: com.busted_moments.client.models.territory.TerritoryModel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.minecraftforge.eventbus.ClassLoaderFactory$ASMClassLoader.loadClass(ClassLoaderFactory.java:110)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 24 more

[20:32:04] [ForkJoinPool.commonPool-worker-6/ERROR]: Exception in event listener not belonging to a feature
java.lang.NoClassDefFoundError: com/busted_moments/client/models/territory/TerritoryModel
	at com.busted_moments.client.models.territory.__TerritoryModel_onMapUpdate_MapUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[net_minecraftforge_eventbus-6.0.3-4a1b1c6840d74a32.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[net_minecraftforge_eventbus-6.0.3-4a1b1c6840d74a32.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[net_minecraftforge_eventbus-6.0.3-4a1b1c6840d74a32.jar:?]
	at com.wynntils.core.WynntilsMod.postEvent(WynntilsMod.java:68) ~[wynntils-0.0.4-beta.14-fabric+MC-1.20.2.jar:?]
	at com.busted_moments.core.events.BaseEvent.post(BaseEvent.java:15) ~[fuy_gg-1.2.1.jar:?]
	at com.busted_moments.client.models.territory.TerritoryModel.lambda$onGameStart$0(TerritoryModel.java:59) ~[fuy_gg-1.2.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
	at com.busted_moments.core.Promise.complete(Promise.java:352) ~[fuy_gg-1.2.1.jar:?]
	at com.busted_moments.core.api.internal.Request.fulfill(Request.java:104) ~[fuy_gg-1.2.1.jar:?]
	at com.busted_moments.core.api.HttpScheduler.onRequestSuccess(HttpScheduler.java:72) ~[fuy_gg-1.2.1.jar:?]
	at com.busted_moments.core.api.HttpScheduler.lambda$sendRequest$3(HttpScheduler.java:59) ~[fuy_gg-1.2.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.busted_moments.client.models.territory.TerritoryModel
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.minecraftforge.eventbus.ClassLoaderFactory$ASMClassLoader.loadClass(ClassLoaderFactory.java:110) ~[net_minecraftforge_eventbus-6.0.3-4a1b1c6840d74a32.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 24 more
```

---------------------------------------------------------------------------

---------------------------------------------------------------------------

---------------------------------------------------------------------------

---------------------------------------------------------------------------

then, starts spamming stuff like:

```java
java.lang.NullPointerException: Cannot invoke "com.busted_moments.core.api.requests.mapstate.MapState.stream()" because "this.LATEST_TERRITORIES" is null
	at com.busted_moments.client.models.territory.TerritoryModel.onTick(TerritoryModel.java:78)
	at com.busted_moments.client.models.territory.__TerritoryModel_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at com.wynntils.core.WynntilsMod.postEvent(WynntilsMod.java:68)
	at com.wynntils.core.events.MixinHelper.post(MixinHelper.java:21)
	at net.minecraft.class_310.handler$eip000$wynntils$tickPost(class_310.java:27112)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:125)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

[20:33:27] [Render thread/ERROR]: Exception in event listener not belonging to a feature
java.lang.NullPointerException: Cannot invoke "com.busted_moments.core.api.requests.mapstate.MapState.stream()" because "this.LATEST_TERRITORIES" is null
	at com.busted_moments.client.models.territory.TerritoryModel.onTick(TerritoryModel.java:78) ~[fuy_gg-1.2.1.jar:?]
	at com.busted_moments.client.models.territory.__TerritoryModel_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[net_minecraftforge_eventbus-6.0.3-4a1b1c6840d74a32.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[net_minecraftforge_eventbus-6.0.3-4a1b1c6840d74a32.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[net_minecraftforge_eventbus-6.0.3-4a1b1c6840d74a32.jar:?]
	at com.wynntils.core.WynntilsMod.postEvent(WynntilsMod.java:68) ~[wynntils-0.0.4-beta.14-fabric+MC-1.20.2.jar:?]
	at com.wynntils.core.events.MixinHelper.post(MixinHelper.java:21) ~[wynntils-0.0.4-beta.14-fabric+MC-1.20.2.jar:?]
	at net.minecraft.class_310.handler$eip000$wynntils$tickPost(class_310.java:27112) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:125) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[20:33:27] [Render thread/ERROR]: Exception caught during firing event: Cannot invoke "com.busted_moments.core.api.requests.mapstate.MapState.stream()" because "this.LATEST_TERRITORIES" is null
	Index: 17
	Listeners:
		0: HIGHEST
		1: ASM: com.busted_moments.client.models.war.timer.TimerModel@ac52e35 onClear(Lcom/wynntils/mc/event/TickEvent;)V
		2: NORMAL
		3: ASM: com.wynntils.core.keybinds.KeyBindManager@3d0a2f02 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		4: ASM: com.wynntils.handlers.chat.ChatHandler@44c85f4d onTick(Lcom/wynntils/mc/event/TickEvent;)V
		5: ASM: com.wynntils.handlers.container.ContainerQueryHandler@2b9438ed onTick(Lcom/wynntils/mc/event/TickEvent;)V
		6: ASM: com.wynntils.models.emeralds.EmeraldModel@1adc1d78 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		7: ASM: com.wynntils.services.chat.ChatTabService@75d2d535 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		8: ASM: com.wynntils.services.discord.DiscordService@54a5a205 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		9: ASM: com.wynntils.services.hades.HadesService@4a630349 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		10: ASM: com.wynntils.services.lootrunpaths.LootrunPathsService@3300ab85 recordMovement(Lcom/wynntils/mc/event/TickEvent;)V
		11: net.minecraftforge.eventbus.EventBus$$Lambda$6915/0x0000000801224468@49fcdfa3
		12: net.minecraftforge.eventbus.EventBus$$Lambda$6915/0x0000000801224468@3f20f7b8
		13: net.minecraftforge.eventbus.EventBus$$Lambda$6915/0x0000000801224468@720bc84b
		14: net.minecraftforge.eventbus.EventBus$$Lambda$6915/0x0000000801224468@1643adb0
		15: net.minecraftforge.eventbus.EventBus$$Lambda$6915/0x0000000801224468@39ed791c
		16: ASM: com.busted_moments.client.keybinds.GuildBankKeybind@4698bb3e onTick(Lcom/wynntils/mc/event/TickEvent;)V
		17: ASM: com.busted_moments.client.models.territory.TerritoryModel@1183e952 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		18: ASM: com.busted_moments.client.features.war.BeaconOnTimersFeature@1fcad601 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		19: ASM: com.wynntils.features.combat.LowHealthVignetteFeature@47e134a6 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		20: ASM: com.wynntils.features.combat.QuickCastFeature@5f8d691c onTick(Lcom/wynntils/mc/event/TickEvent;)V
		21: ASM: com.wynntils.features.combat.RangeVisualizerFeature@5d73322c onTick(Lcom/wynntils/mc/event/TickEvent;)V
		22: ASM: com.wynntils.features.combat.SpellCastVignetteFeature@1233814d onTick(Lcom/wynntils/mc/event/TickEvent;)V
		23: ASM: com.wynntils.features.map.BeaconBeamFeature@b24d7d5 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		24: ASM: com.wynntils.overlays.minimap.CoordinateOverlay@1eecbf8c onTick(Lcom/wynntils/mc/event/TickEvent;)V
		25: ASM: com.wynntils.overlays.minimap.TerritoryOverlay@118b8c59 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		26: ASM: com.wynntils.overlays.ArrowShieldTrackerOverlay@5e9f843e onTick(Lcom/wynntils/mc/event/TickEvent;)V
		27: ASM: com.wynntils.overlays.CombatExperienceOverlay@5b20e3d3 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		28: ASM: com.wynntils.overlays.gamebars.HealthBarOverlay@393dc0fa onTick(Lcom/wynntils/mc/event/TickEvent;)V
		29: ASM: com.wynntils.overlays.gamebars.BloodPoolBarOverlay@232a506a onTick(Lcom/wynntils/mc/event/TickEvent;)V
		30: ASM: com.wynntils.overlays.gamebars.ManaBarOverlay@4147d6c3 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		31: ASM: com.wynntils.overlays.gamebars.ManaBankBarOverlay@a4aa5be onTick(Lcom/wynntils/mc/event/TickEvent;)V
		32: ASM: com.wynntils.overlays.gamebars.FocusBarOverlay@5d279e1d onTick(Lcom/wynntils/mc/event/TickEvent;)V
		33: ASM: com.wynntils.overlays.gamebars.AwakenedProgressBarOverlay@2c7f2cd3 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		34: ASM: com.wynntils.overlays.gamebars.CorruptedBarOverlay@53f11651 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		35: ASM: com.wynntils.overlays.lootrun.LootrunTaskNameOverlay@66ce96fc onTick(Lcom/wynntils/mc/event/TickEvent;)V
		36: ASM: com.wynntils.overlays.lootrun.LootrunBeaconCountOverlay@7bbd1617 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		37: ASM: com.wynntils.overlays.MobTotemTimerOverlay@10c405d onTick(Lcom/wynntils/mc/event/TickEvent;)V
		38: ASM: com.wynntils.overlays.ShamanMaskOverlay@703f8aca onTick(Lcom/wynntils/mc/event/TickEvent;)V
		39: ASM: com.wynntils.overlays.ShamanTotemTimerOverlay@4f74c5b8 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		40: ASM: com.wynntils.overlays.SpellCastMessageOverlay@278aefe0 onTick(Lcom/wynntils/mc/event/TickEvent;)V
		41: ASM: com.wynntils.overlays.stopwatch.StopwatchOverlay@175bcb0d onTick(Lcom/wynntils/mc/event/TickEvent;)V
		42: ASM: com.wynntils.overlays.TowerAuraTimerOverlay@217563a onTick(Lcom/wynntils/mc/event/TickEvent;)V
		43: LOWEST
		44: ASM: com.busted_moments.client.models.war.WarModel@2cbc4981 onTick(Lcom/wynntils/mc/event/TickEvent;)V
```

**Comment by rune0018** [comment]
tbh this looks like an api issue on your end i took a look at the souce code to find the url for the territori list but yes this needs a failsafe incase it fails or atleast stop the itirator from trying to run it

>souce url btw https://thesimpleones.net/api/territoryList

**Comment by Essentuan** [comment]
I have a hard time believing the two issues are related at all. The second issue you pointed out I will fix though.
